name: Bug report
description: Report incorrect PR Sheriff behavior
body:
  - type: textarea
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal reproduction
    validations:
      required: true
  - type: input
    attributes:
      label: PR Sheriff and Python versions
    validations:
      required: true
